authApp/urls.py
from django.urls import path
from .views import *


app_name='authApp'

urlpatterns=[
    path('',loginview,name='login'),
    path('logout/',logoutView,name='logout'),
    path('forget-password/',frgtPwd,name='frgtPwd'),
    path('register/',register,name='register'),
    path('chck-usrname/',checkUserName,name='chck_usrname'),
    path('chck-email/',checkEmail,name='chck_email'),

]

iamdb/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('iamdbApp.urls')),
    path('login/', include('authApp.urls')),
]

authApp/models.py
from django.db import models
from iamdbApp.models import AuthUser
# Create your models here.

authApp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User as UserModel
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import authenticate, login,logout
from django.contrib import messages
from django.http import FileResponse, JsonResponse
# from iamdbApp.models import AuthUser
import datetime
# Create your views here.

def loginview(request):
    if request.user.is_authenticated:
        return render(request,'logoutFst.html')

    if request.method=='POST':
        print('coming')
        username=request.POST['username']
        password=request.POST['password']
        # nwpassword=
        # user=authenticate(username=username,password=password)
        try:
            user=UserModel.objects.get(email=username,password=password)
            # ourModelusr=User.objects.get(email=email,password=password)
            # print(ourModelusr.userroleid)
            # if user is not None:
            # messages.info(request,'coming here..')
            if user.is_active:
                login(request, user)
                # ourModelusr = User.objects.get(id=userObj.id)
                # if ourModelusr.userroleid == 2:
                #     return redirect('signin:home')
                return redirect('iamdbApp:index')
            else:
                messages.info(request,'User is locked.')
        except ObjectDoesNotExist:
            messages.info(request,'Invalid Email Id or Password.')
        # return redirect('login:login')

    return render(request,'login.html',{'user':request.user})


def logoutView(request):
    logout(request)
    return redirect('authApp:login')

def frgtPwd(request):
    if request.method == 'POST':
        pass
    else:
        return render(request, 'frgt.html')

def register(request):
    if request.user.is_authenticated:
        return render(request,'logoutFst.html')
    if request.method == 'POST':
        usr=UserModel(email=request.POST['email'],username=request.POST['username'],password=request.POST['password'],is_superuser=0,is_staff=0,is_active=1,date_joined=datetime.datetime.today(),first_name="foo",last_name='foo' )
        usr.save()
        login(request, usr)
        return redirect('iamdbApp:index')
    else:
        return render(request, 'register.html')

def checkUserName(request):
    if UserModel.objects.filter(username=request.GET.get('uname')).count() >= 1:
        rslt=1
    else:
        rslt = 0
    return JsonResponse(data={'rslt':rslt})

def checkEmail(request):
    if UserModel.objects.filter(email=request.GET.get('mail')).count() >= 1:
        rslt=1
    else:
        rslt = 0
    return JsonResponse(data={'rslt':rslt})

authApp/templates/frgt.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Forgot Password</title>
</head>
<body>

</body>
</html>

authApp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login Page</title>
    {% load static %}
    <link href="{% static 'authApp/css/login.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
    <header>
        {% include 'iamdbApp/header.html' %}
    </header>
    <article>


        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
             <!--<span style="color:white;">{{user}}</span>-->
            <table class="loginTbl">
                <tr>
                    <td><h1>Login</h1></td>
                </tr>
                <!--<tr>-->
                    <!--<td><label>Username</label></td>-->
                <!--</tr>-->
                <tr>
                    <td><input type="text" name="username" required placeholder="Username"></td>
                </tr>
                <!--<tr>-->
                    <!--<td><label>Password</label></td>-->
                <!--</tr>-->
                <tr>
                    <td><input type="password" name="password" required placeholder="Password"></td>
                </tr>
                <tr style="direction:rtl;">
                    <td style=""><br><button type="submit" class="sbmtBtn" style="">Login</button> &nbsp;&nbsp;&nbsp;<a href="{% url 'authApp:frgtPwd' %}">?Forgot Password</a> </td>
                </tr>
                {% for msg in messages %}
                <tr>
                    <td style="color:red;">{{msg}}</td>
                </tr>
                {% endfor %}
                <tr style="text-align:center;">
                    <td><br><br><br><a href="{% url 'authApp:register' %}">New user registration</a> </td>
                </tr>
            </table>
        </form>
    </article>
</body>
</html>

authApp/templates/logoutFst.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout First</title>
    {% load static %}
    <link href="{% static 'iamdbApp/css/uni.css' %}" rel="stylesheet" type="text/css">
</head>
<body style="text-align:center;">
    <header>
        {% include 'iamdbApp/header.html' %}
    </header>
    <p style="color:black;font-size:30px;">
        <br>
        <br>
        <br>
        <br>
        <br>You are already logged in!
        <br> <a href="{% url 'authApp:logout' %}">click here to logout</a></p>
</body>
</html>

authApp/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration Page</title>
    {% load static %}
    <link href="{% static 'authApp/css/login.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'authApp/css/register.css' %}" rel="stylesheet" type="text/css">

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <!-- <script src="{% static 'authApp/js/jquery.min.js' %}" rel="script"></script> -->
    <!--<script src="{% static 'authApp/js/register.js' %}" rel="script"></script>-->
    <!--<script src="static 'authApp/js/parsley.min.js' "></script>-->
    <link href="{% static 'iamdbApp/css/uni.css' %}" rel="stylesheet" type="text/css">
    <script>
        $(document).ready(function(){
            $('#username').focus(function(){
                $('#unqUnameMsg').hide();
            });
            $('#username').focusout(function(){
                $.ajax({
                    url:"{% url 'authApp:chck_usrname' %}",
                    data:{
                        'uname':$(this).val(),
                    },
                    dataType:'json',
                    success:function(data){
                        if(data.rslt==1){
                            $('#unqUnameMsg').show();
                        }
                    },
                });
            });
            $('#email').focus(function(){
                $('#unqMailMsg').hide();
            });
            $('#email').focusout(function(){
                $.ajax({
                    url:"{% url 'authApp:chck_email' %}",
                    data:{
                        'mail':$(this).val(),
                    },
                    dataType:'json',
                    success:function(data){
                        if(data.rslt==1){
                            $('#unqMailMsg').show();
                        }
                    },
                });
            });
        });
        function check(){
            if($('#unqUnameMsg').is(':visible') || $('#unqMailMsg').is(':visible')){
                return false;
            }
        }
    </script>
</head>
<body>
    <header>
        {% include 'iamdbApp/header.html' %}
    </header>
    <article>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table class="fstStage loginTbl">
                <tr>
                    <td>
                        <h4 style="text-align:center;text-transform:uppercase;font-family:Consolas;color:white;"><span style="font-size:30px;">R</span>egister</h4>
                    </td>
                </tr>
                <tr>
                    <td>
                        <input type="email" id="email" name="email" placeholder="Email" required>
                        <br>
                        <span id="unqMailMsg" hidden>Account with this email already exist!</span>
                    </td>
                </tr>
                <!--<tr>-->
                    <!--<td><button class="sbmtBtn" id="nxtBtn" type="button" style="outline:none;">Next</button></td>-->
                <!--</tr>-->
            <!--</table>-->
            <!--<table class="scndStage loginTbl" id="id_scndStage" style="margin-top:0;">-->
                <!--<tr style="">-->
                    <!--<td></td>-->
                <!--</tr>-->
                <!--<tr>-->
                    <!--<td>-->
                        <!--<h4 style="text-align:center;text-transform:uppercase;font-family:Consolas;color:white;"><span style="font-size:30px;">R</span>egister</h4>-->
                    <!--</td>-->
                <!--</tr>-->
                <tr class="scndStage">
                    <td>
                        <input type="text" id="username" name="username" placeholder="Username" required>
                        <br>
                        <span id="unqUnameMsg" hidden>Username already taken!</span>
                    </td>
                </tr>
                <!--<tr>-->
                    <!--<td><label>Password</label></td>-->
                <!--</tr>-->
                <tr class="scndStage">
                    <td><input type="password" id="password" name="password" placeholder="Password" required></td>
                </tr>
                <tr class="scndStage">
                    <td><input type="password" id="confirm_password" placeholder="Confirm Password" required></td>
                </tr>

                <tr class="scndStage" style="text-align:center;">
                    <td><br><button class="sbmtBtn" type="submit"  style="float:none;width:200px;" onclick="return check()">Create Account</button></td>
                </tr>
            </table>
        </form>
    </article>
</body>
</html>