authApp/urls.py
from django.urls import path
from .views import *


app_name='authApp'

urlpatterns=[
    path('',loginview,name='login'),
    path('logout/',logoutView,name='logout'),
    path('forget-password/',frgtPwd,name='frgtPwd'),
    path('register/',register,name='register'),
    path('chck-usrname/',checkUserName,name='chck_usrname'),
    path('chck-email/',checkEmail,name='chck_email'),

]

iamdb/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('iamdbApp.urls')),
    path('login/', include('authApp.urls')),
]

iamdbApp/urls.py
from django.urls import path
from .views import *


app_name='iamdbApp'

urlpatterns=[
    path('',index,name='index'),

    path('search/',search,name='search'),
    path('wishlist-add/',addToWishList,name='wishlist-add'),
    path('watchlist-add/',addToWatchList,name='watchlist-add'),


    path('user-profile/',userProfile,name='user-profile'),
    path('user-profile/backend/<int:pk>/',UserDetailAndUpdate.as_view(),name='user-profile-backend'),
]

iamdbApp/models.py
from django.db import models

# Create your models here.

from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)
    name = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)

class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()
    last_name = models.CharField(max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    action_flag = models.PositiveSmallIntegerField()

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'

class WatchList(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    contentId = models.CharField(unique=True,max_length=20)

    class Meta:
        managed = True
        unique_together = (('user', 'contentId'),)

class WishList(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    contentId = models.CharField(unique=True,max_length=20)

    class Meta:
        managed = True
        unique_together = (('user', 'contentId'),)

iamdbApp/forms.py
from django import forms
from .models import *

class UserForm(forms.ModelForm):
    class Meta:
        model=AuthUser
        fields = ['username', 'first_name', 'last_name', 'email', 'date_joined']

iamdbApp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from imdbpie import Imdb
from .forms import UserForm
from .models import *
from django.views import generic,View
from django.urls import reverse_lazy

# Create your views here..
imdb = Imdb()

@login_required
def index(request):
    return render(request,'iamdbApp/index.html',context={})

def search(request):
    txt = request.GET.get('srch_txt')
    # movie_details = None
    print(txt)
    movie_details = imdb.search_for_title(txt)

    print(movie_details)
    return JsonResponse(data={'rslt':txt,'movie_details_list':movie_details})

def addToWishList(request):
    imdbId = request.GET.get('imdbId')
    print(imdbId)
    rslt=1
    try:
        if imdbId in WatchList.objects.filter(user=AuthUser.objects.get(id=request.user.id)).values('contentId'):
            rslt=-1
        else:
            WatchList(user=AuthUser.objects.get(id=request.user.id),contentId=imdbId).save()
    except:
        rslt=0
    print(rslt)
    return JsonResponse(data={'rslt': rslt})

def addToWatchList(request):
    imdbId = request.GET.get('imdbId')
    print(imdbId)
    rslt = 1
    try:
        if imdbId in WishList.objects.filter(user=AuthUser.objects.get(id=request.user.id)).values('contentId'):
            rslt = -1
        else:
            WishList(user=AuthUser.objects.get(id=request.user.id), contentId=imdbId).save()
    except:
        rslt = 0
    print(rslt)
    return JsonResponse(data={'rslt': rslt})

@login_required
def userProfile(request):
    return UserDetailAndUpdate.as_view()(request,pk=request.user.id)

# class UserDetailView(generic.DetailView):
#     model=AuthUser
#     template_name = 'iamdbApp/user-profile.html'

class UserDetailAndUpdate(generic.UpdateView):
    model = AuthUser
    fields = ['username', 'first_name', 'last_name', 'email', 'date_joined']
    success_url = reverse_lazy('iamdbApp:user-profile')
    # fields = '__all__'

# thas was for registration which i wss using in show and update details
# class UserProfileForm(View):
#     def get(self, request):
#         usr_form = UserForm(instance=AuthUser())
#         template = 'iamdbApp/user-profile.html'
#         context = {'usr_form': usr_form}
#         return render(request, template, context)
#
#     def post(self, request):
#         # context = {}
#         usr_form  = UserForm(request.POST, instance=AuthUser())
#
#         if usr_form.is_valid():
#             new_adv = usr_form.save(commit=False)
#             new_adv.auth_user = User.objects.get(email=request.user.email)
#             print(new_adv.auth_user.email)
#             print(cart_forms)
#             new_adv.save()
#             for cart_form in cart_forms:
#                 new_cart = cart_form.save(commit=False)
#                 new_cart.id = new_adv
#                 # new_cart.auth_user=User.objects.get(id=1)
#                 new_cart.save()
#                 # print(new_cart.noofdays)
#             return redirect("/adminsite/list/Cartdetail")
#         context = {'adv_form': adv_form, 'cart_forms': cart_forms}
#         return render(request, 'admm/new_cart.html', context)
#     # return render(request,'iamdbApp/user-profile.html',context={})

iamdbApp/templates/iamdbApp/authuser_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Profile</title>
    {% load static %}
    <style>
        input{
            padding:5px;
        }
    </style>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <!-- <script src="{% static 'iamdbApp/js/jquery.min.js' %}"></script> -->
    <script>
        $(function(){
            $('tbody input').css('border','none');
            $('tbody input').css('outline','none');
            $('tbody input').prop('readonly',true);
            $('.postBtns').hide();

            $('#editBtn').click(function(){
                $('tbody input').css('border','1px solid');
                $('tbody input').css('outline','default');
                $('tbody input').prop('readonly',false);
                $('.postBtns').show();
                $(this).hide();
            });
            $('#cnclBtn').click(function(){
                $('tbody input').css('border','none');
                $('tbody input').css('outline','none');
                $('tbody input').prop('readonly',true);
                $('.postBtns').hide();
                $('#editBtn').show();
            });
        });
    </script>
</head>
<body>
    <header>
        {% include 'iamdbApp/header.html' %}
    </header>
    <br>
    <br>
    <br>
    <form action="" method='post' enctype='multipart/form-data'>
        {% csrf_token %}
        <table style="width:90%;text-align:center;">
            <thead>
                <!--<tr>-->
                    <!--<td style="text-align:right;" colspan="2"><i class="fas fa-ellipsis-v" style="font-size:30px;color:gray;"></i> </td>-->
                <!--</tr>-->
                <tr>
                    <td style="padding:10px;" colspan="2"> <h1>My Profile</h1> </td>
                </tr>
            </thead>
            <tbody style="">
                <tr>
                    <td colspan="2"> <img src="" height="200px" width="200px" style="border:1px solid"> </td>
                </tr>
                {{form.as_table}}
                <tr>
                    <td colspan="2"> <button id="editBtn" class="btn btn-primary" type="button">Edit Details</button> <button class="postBtns btn btn-success" type="submit">Update</button> <button class="postBtns btn btn-primary" id="cnclBtn" type="button">Cancel</button></td>
                </tr>
            </tbody>
        </table>
    </form>
</body>
</html>

iamdbApp/templates/iamdbApp/header.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Nav Bar</title>
        {% load static %}
        <link href="{% static 'iamdbApp/css/uni.css' %}" rel="stylesheet">
        <link href="{% static 'iamdbApp/fontawesome-free-5.12.0-web/css/all.css' %}" rel="stylesheet" type="text/css">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <!-- <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script> -->
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <script>
            var srchUrl="{% url 'iamdbApp:search' %}";
            var add2wishUrl="{% url 'iamdbApp:wishlist-add' %}";
            var add2watchUrl="{% url 'iamdbApp:watchlist-add' %}";
        </script>
        <script src="{% static 'iamdbApp/js/header.js' %}"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <!-- <link href="{% static 'iamdbApp/bootstrap4.4.1/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"> -->
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'iamdbApp:index' %}" style="font-size:40px;">Corns<span style="color:limegreen;">Pop</span></a>

            {% if user.is_authenticated %}
            <!--<div>-->
                <ul style="margin-left:300px;padding-top:10px;">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:lightgray;">
                            <i class="fas fa-user" style="color:lightgray;"></i>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown" >
                            <a class="dropdown-item" href="{% url 'iamdbApp:user-profile' %}">My Profile</a>
                            <a class="dropdown-item" href="">Favourite List <i class="fas fa-heart"></i></a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'authApp:logout' %}">Logout <i class="fas fa-sign-out-alt"></i></a>
                        </div>
                    </li>
                </ul>
            <!--</div>-->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class=""><i class="fas fa-search" style="color:lightgray;"></i></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <!--<li class="nav-item active">-->
                  <!--<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
                <!--</li>-->
                    <li>
                        <form class="form-inline my-2 my-lg-0">
                            <input id="searchBox" class="form-control mr-sm-2" list="listHere" type="search" placeholder="Search" aria-label="Search" style="width:80%;font-size:30px;" NAME="srch_txt">
                            <!--<button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>-->

                        </form>
                    </li>


                <!--<li class="nav-item">-->
                  <!--<a class="nav-link" href="#">Link</a>-->
                <!--</li>-->

                <!--<li class="nav-item">-->
                  <!--<a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
                <!--</li>-->
              </ul>

            </div>
            {% endif %}
          </nav>
        <div class="container-fluid"  style="color:black;background-color:white;width:80%;height:300px;border:1px solid black;overflow-y:scroll;">
            <table style="" id="movieListSrch">

            </table>
        </div>
    </body>
</html>

iamdbApp/templates/iamdbApp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    {% load static %}
    <link href="{% static 'iamdbApp/css/uni.css' %}" rel="stylesheet">
    <link href="{% static 'iamdbApp/css/index.css' %}" rel="stylesheet">
</head>
<body>
    <header>
        {% include 'iamdbApp/header.html' %}
    </header>
    <article >

    </article>
</body>
</html>